# Generated by Django 2.1.7 on 2019-03-28 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_processo', '0001_initial'),
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro_processo.Planilha'),
        ),
    ]
